### PR TITLE
fix: item qty validation on adding supplier item

### PR DESCRIPTION
**Pull request by parasg1999**
### What is the current behavior?
When adding an item, the item quantity is accepting negative values.

### What is the new behavior if this PR is merged?
The validation will be checked before saving the changes.

##### This PR has:

-  [x] Commit messages that are correctly formatted
-  [ ] Feature list updated for newly introduced code

This PR is a small change 
that fixes #

**Developers**

@parasg1999

### CODE REVIEW

**Comment by prvnbist** [comment]
There's also a `leadTimeUnit` below the line you fixed, does it also require same fix?

**Comment by parasg1999** [comment]
That is a dropdown (minutes, hours, days), so there is no need for this validation

**Comment by prvnbist** [comment]
Pro Tip: Always name your branches with what it's adding/fixing to the code

**Comment by parasg1999** [comment]
@prvnbist Will take care about that. Thank you! :smile:

**Pull request merged**
